/**
 * Versioned long-term achievement definitions (campaign 003 convergence,
 * constitution §18). IDs are canonical keys — never reuse an id for a
 * different achievement. The orchestrator seeds this list at startup
 * (`achievements.upsertDefinition(toDbAchievementDefinition(a))`) and the
 * Profile/rewards surfaces surface unlock/claim/equip states.
 *
 * The catalog is organized by category and tier so the engagement layer
 * rewards breadth across the whole library (every cognitive domain, plus
 * streak/perfect-play milestones) rather than only raw session/XP volume.
 *
 * IMPORTANT backward-compat note: the baseline four (`ach-first`, `ach-25`,
 * `ach-100`, `ach-xp-5000`) keep their exact original criteria and order so
 * existing evaluation tests stay stable. Every newer achievement has a goal
 * strictly above the values exercised by those tests ({ sessionCount: 25,
 * totalXp: 6000 }), so they never change the original met-set.
 */
import type { AchievementDef } from "./types";

export const ACHIEVEMENT_DEFINITIONS_V1: readonly AchievementDef[] = [
  // ---- Baseline milestones (unchanged criteria, now categorized/tiered) ----
  Object.freeze({
    id: "ach-first",
    title: "First Steps",
    description: "Complete your first training session.",
    category: "Milestone",
    tier: "bronze",
    criteria: { type: "session-count", goal: 1 },
    rewardXp: 50,
    rewardCurrency: 25,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-25",
    title: "Getting Regular",
    description: "Complete 25 sessions in total.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "session-count", goal: 25 },
    rewardXp: 250,
    rewardCurrency: 100,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-100",
    title: "Century Club",
    description: "Complete 100 sessions in total.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "session-count", goal: 100 },
    rewardXp: 600,
    rewardCurrency: 250,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-xp-5000",
    title: "XP Voyager",
    description: "Earn 5,000 lifetime XP.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "total-xp", goal: 5000 },
    rewardXp: 1000,
    rewardCurrency: 500,
    version: 1,
  } satisfies AchievementDef),

  // ---- Volume milestones (higher goals; do not affect baseline tests) ----
  Object.freeze({
    id: "ach-250",
    title: "Dedicated Mind",
    description: "Complete 250 sessions in total.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "session-count", goal: 250 },
    rewardXp: 1500,
    rewardCurrency: 600,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-500",
    title: "Training Sage",
    description: "Complete 500 sessions in total.",
    category: "Milestone",
    tier: "platinum",
    criteria: { type: "session-count", goal: 500 },
    rewardXp: 3000,
    rewardCurrency: 1200,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-xp-25000",
    title: "XP Navigator",
    description: "Earn 25,000 lifetime XP.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "total-xp", goal: 25000 },
    rewardXp: 2500,
    rewardCurrency: 1000,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-xp-75000",
    title: "XP Luminary",
    description: "Earn 75,000 lifetime XP.",
    category: "Milestone",
    tier: "platinum",
    criteria: { type: "total-xp", goal: 75000 },
    rewardXp: 5000,
    rewardCurrency: 2000,
    version: 1,
  } satisfies AchievementDef),

  // ---- Longest-streak milestones (rewards consistent daily practice) ----
  Object.freeze({
    id: "ach-streak-7",
    title: "Week Strong",
    description: "Reach a 7-day streak.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "longest-streak", goal: 7 },
    rewardXp: 300,
    rewardCurrency: 150,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-streak-30",
    title: "Monthly Devotion",
    description: "Reach a 30-day streak.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "longest-streak", goal: 30 },
    rewardXp: 1200,
    rewardCurrency: 500,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-streak-100",
    title: "Unbreakable",
    description: "Reach a 100-day streak.",
    category: "Milestone",
    tier: "platinum",
    criteria: { type: "longest-streak", goal: 100 },
    rewardXp: 4000,
    rewardCurrency: 1500,
    version: 1,
  } satisfies AchievementDef),

  // ---- Perfect-play milestones (high normalized performance) ----
  Object.freeze({
    id: "ach-perfect-10",
    title: "Sharp Shooter",
    description: "Complete 10 sessions at 90%+ performance.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "perfect-sessions", goal: 10, threshold: 0.9 },
    rewardXp: 400,
    rewardCurrency: 150,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-perfect-50",
    title: "Flawless",
    description: "Complete 50 sessions at 90%+ performance.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "perfect-sessions", goal: 50, threshold: 0.9 },
    rewardXp: 1500,
    rewardCurrency: 600,
    version: 1,
  } satisfies AchievementDef),

  // ---- Per-domain lifetime volume (breadth across the library) ----
  Object.freeze({
    id: "ach-domain-memory",
    title: "Memory Keeper",
    description: "Complete 50 Memory sessions.",
    category: "Memory",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Memory", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-attention",
    title: "Focused",
    description: "Complete 50 Attention sessions.",
    category: "Attention",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Attention", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-speed",
    title: "Quick Thinker",
    description: "Complete 50 Speed sessions.",
    category: "Speed",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Speed", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-math",
    title: "Number Cruncher",
    description: "Complete 50 Math sessions.",
    category: "Math",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Math", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-language",
    title: "Wordsmith",
    description: "Complete 50 Language sessions.",
    category: "Language",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Language", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-logic",
    title: "Problem Solver",
    description: "Complete 50 Logic & Problem Solving sessions.",
    category: "Logic",
    tier: "gold",
    criteria: {
      type: "domain-sessions",
      domain: "Logic & Problem Solving",
      goal: 50,
    },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-flexibility",
    title: "Adaptable",
    description: "Complete 50 Flexibility sessions.",
    category: "Flexibility",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Flexibility", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domain-spatial",
    title: "Spatial Thinker",
    description: "Complete 50 Spatial sessions.",
    category: "Spatial",
    tier: "gold",
    criteria: { type: "domain-sessions", domain: "Spatial", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),

  // ---- Engagement-wave-02 expansions (campaign 006, section B) ----
  // Volume depth.
  Object.freeze({
    id: "ach-1000",
    title: "Session Veteran",
    description: "Complete 1,000 sessions in total.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "session-count", goal: 1000 },
    rewardXp: 5000,
    rewardCurrency: 2000,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-2500",
    title: "Session Legend",
    description: "Complete 2,500 sessions in total.",
    category: "Milestone",
    tier: "platinum",
    criteria: { type: "session-count", goal: 2500 },
    rewardXp: 12000,
    rewardCurrency: 5000,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-xp-150000",
    title: "XP Grandmaster",
    description: "Earn 150,000 lifetime XP.",
    category: "Milestone",
    tier: "platinum",
    criteria: { type: "total-xp", goal: 150000 },
    rewardXp: 10000,
    rewardCurrency: 4000,
    version: 1,
  } satisfies AchievementDef),
  // Breadth / diverse-game play.
  Object.freeze({
    id: "ach-games-5",
    title: "Explorer",
    description: "Play 5 different games.",
    category: "Milestone",
    tier: "bronze",
    criteria: { type: "distinct-games", goal: 5 },
    rewardXp: 100,
    rewardCurrency: 50,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-games-12",
    title: "Collector",
    description: "Play 12 different games.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "distinct-games", goal: 12 },
    rewardXp: 300,
    rewardCurrency: 150,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-domains-all",
    title: "Well Rounded",
    description: "Train in all 8 cognitive categories.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "domain-coverage", goal: 8 },
    rewardXp: 800,
    rewardCurrency: 400,
    version: 1,
  } satisfies AchievementDef),
  // Category mastery depth.
  Object.freeze({
    id: "ach-domain-memory-100",
    title: "Memory Master",
    description: "Complete 100 Memory sessions.",
    category: "Memory",
    tier: "platinum",
    criteria: { type: "domain-sessions", domain: "Memory", goal: 100 },
    rewardXp: 1500,
    rewardCurrency: 600,
    version: 1,
  } satisfies AchievementDef),
  // Consistency (distinct active days).
  Object.freeze({
    id: "ach-active-7",
    title: "Weekly Habit",
    description: "Be active on 7 different days.",
    category: "Milestone",
    tier: "bronze",
    criteria: { type: "active-days", goal: 7 },
    rewardXp: 120,
    rewardCurrency: 60,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-active-30",
    title: "Monthly Habit",
    description: "Be active on 30 different days.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "active-days", goal: 30 },
    rewardXp: 400,
    rewardCurrency: 200,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-active-100",
    title: "Daily Devotion",
    description: "Be active on 100 different days.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "active-days", goal: 100 },
    rewardXp: 1500,
    rewardCurrency: 600,
    version: 1,
  } satisfies AchievementDef),
  // Accuracy + personal-best progression.
  Object.freeze({
    id: "ach-acc-25",
    title: "Sharp",
    description: "Complete 25 sessions at 80%+ performance.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "accuracy-sessions", goal: 25, threshold: 0.8 },
    rewardXp: 200,
    rewardCurrency: 100,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-acc-100",
    title: "Marksman",
    description: "Complete 100 sessions at 80%+ performance.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "accuracy-sessions", goal: 100, threshold: 0.8 },
    rewardXp: 800,
    rewardCurrency: 400,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-best-90",
    title: "Precision",
    description: "Reach 90%+ performance in a single session.",
    category: "Milestone",
    tier: "silver",
    criteria: { type: "best-normalized", goal: 0.9 },
    rewardXp: 250,
    rewardCurrency: 120,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-best-98",
    title: "Flawless Focus",
    description: "Reach 98%+ performance in a single session.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "best-normalized", goal: 0.98 },
    rewardXp: 600,
    rewardCurrency: 300,
    version: 1,
  } satisfies AchievementDef),
  // Workout completion.
  Object.freeze({
    id: "ach-workout-10",
    title: "Routine Builder",
    description: "Complete 10 daily workouts.",
    category: "Milestone",
    tier: "bronze",
    criteria: { type: "workout-completions", goal: 10 },
    rewardXp: 150,
    rewardCurrency: 75,
    version: 1,
  } satisfies AchievementDef),
  Object.freeze({
    id: "ach-workout-50",
    title: "Routine Master",
    description: "Complete 50 daily workouts.",
    category: "Milestone",
    tier: "gold",
    criteria: { type: "workout-completions", goal: 50 },
    rewardXp: 800,
    rewardCurrency: 400,
    version: 1,
  } satisfies AchievementDef),
] as const;
