/**
 * Workout Engine V2 — metadata model + instance identity.
 *
 * A workout *instance* is one persisted row in `workout_instances`. Its
 * primary key (the `date` column) is treated as a string **instance key**:
 *
 * - the default daily workout keeps the bare local date (`2026-08-21`) as its
 *   key — byte-identical to the pre-V2 format, so every existing row, query
 *   and consumer keeps working unchanged;
 * - template workouts (focus/domain-targeted structures started by the
 *   player; see `templates.ts`) use namespaced keys
 *   `<date>::<templateId>::<length>`, which the same TEXT primary key stores
 *   without any schema change. `parseInstanceKey` is the single decoder.
 *
 * Metadata (template id, length, focus, generation inputs) is versioned via
 * {@link WORKOUT_METADATA_VERSION}. It travels on the in-memory instance and
 * is persisted into the `metadata_json` column introduced by schema v10;
 * legacy adapters that do not expose the column still degrade gracefully.
 * Selection itself stays deterministic:
 * re-running a selection with the recorded inputs always reproduces the same
 * game list for the same version.
 */

import type { GameCategory } from "@/sdk";
import type { WorkoutSelectionReason } from "./personalize";

/**
 * Schema version of {@link WorkoutMetadata}. Bump whenever the shape changes
 * so persisted/serialized metadata can be interpreted correctly.
 */
export const WORKOUT_METADATA_VERSION = 3;

/**
 * Selector version stamped onto template-workout instances. The legacy daily
 * selector (`@/workout/today` + `personalize`) persists `seedVersion: 1`;
 * V2 template selection used 2; V3 signal-ranked selection uses 3 so new
 * instances cannot be mistaken for rows generated by the older ordering.
 */
export const WORKOUT_SELECTION_SEED_VERSION = 3;

/** Workout length variants (constitution §14: "normally four games" = standard). */
export type WorkoutLength = "short" | "standard" | "extended";

/** Whether an instance is the default daily mix or a player-started template. */
export type WorkoutKind = "daily" | "template";

/** True when `value` is one of the named workout lengths. */
export function isWorkoutLength(value: unknown): value is WorkoutLength {
  return (
    value === "short" || value === "standard" || value === "extended"
  );
}

/**
 * Snapshot of the inputs a selection was computed from (provenance,
 * constitution §10/§21: generated artifacts record their versions and
 * inputs). Stored with the instance metadata when persistence allows.
 */
export interface WorkoutGenerationInputs {
  /** Domain rating snapshot at creation time (domain → rating). */
  domainRatings: Record<string, number>;
  /** Recently played game ids at creation time (newest first). */
  recentGameIds: string[];
  /** Canonical RNG seed the selection was drawn from. */
  seed: string;
  /** Complete aggregate evidence used by the V3 signal scorer. */
  aggregates?: readonly WorkoutAggregateEvidence[];
  /** Complete recent-session evidence used by the V3 trend/fatigue signals. */
  recentSessions?: readonly WorkoutRecentSessionEvidence[];
  /** Clock captured for the V3 staleness signal. */
  nowMs?: number;
}

export interface WorkoutAggregateEvidence {
  gameId: string;
  count: number;
  avgNormalized: number;
  bestNormalized: number;
  lastCompletedAt: number;
}

export interface WorkoutRecentSessionEvidence {
  gameId: string;
  normalizedResult: number;
  completedAt: number;
}

/** Versioned metadata attached to every V2 workout instance. */
export interface WorkoutMetadata {
  /** {@link WORKOUT_METADATA_VERSION} of the producing engine. */
  version: number;
  kind: WorkoutKind;
  /** Stable template id (`daily-mix` for the default; see `templates.ts`). */
  templateId: string;
  length: WorkoutLength;
  /** Targeted cognitive domain, or null for mixed workouts. */
  focus: GameCategory | null;
  /** Generation-input snapshot (present when the caller supplied one). */
  inputs?: WorkoutGenerationInputs;
  /** Selector version used to produce the recorded order (V3+ rows). */
  selectionVersion?: number;
  /**
   * Selection-order personalization reasons recorded at creation time (see
   * `reasons.ts`). Additive OPTIONAL field (provenance, not load-bearing):
   * v1 producers never wrote it and both old and new readers interpret rows
   * correctly without a version bump — old parsers silently ignore unknown
   * JSON keys, new parsers treat absence as undefined. Consumers must treat
   * recorded reasons as valid only while they still match the persisted
   * selection (see `alignedRecordedReasons` in `reasons.ts`): rerolls and
   * catalog reconciliation can change `gameIds` after the fact.
   */
  reasons?: WorkoutSelectionReason[];
}

/* ------------------------------------------------------------------ *
 * Instance keys
 * ------------------------------------------------------------------ */

/** Separator between the date and the template parts of an instance key. */
export const INSTANCE_KEY_SEPARATOR = "::";

/** Key of the default daily workout for a local calendar date. */
export function dailyInstanceKey(date: string): string {
  return date;
}

/** Key of a template workout instance for `(date, templateId, length)`. */
export function templateInstanceKey(
  date: string,
  templateId: string,
  length: WorkoutLength,
): string {
  return `${date}${INSTANCE_KEY_SEPARATOR}${templateId}${INSTANCE_KEY_SEPARATOR}${length}`;
}

/** Decoded parts of an instance key (see module comment). */
export interface ParsedInstanceKey {
  /** Local calendar date (YYYY-MM-DD) the instance belongs to. */
  date: string;
  kind: WorkoutKind;
  /** Template id for template keys; null for daily keys (and malformed ones). */
  templateId: string | null;
  /** Length variant for template keys; null for daily keys (and malformed). */
  length: WorkoutLength | null;
}

/**
 * Decode an instance key. Unknown/malformed shapes never throw: they degrade
 * to `{ kind: 'template', templateId: null, length: null }` keyed by their
 * leading date-like segment, so history rendering stays robust against
 * future key formats instead of crashing on them.
 */
export function parseInstanceKey(key: string): ParsedInstanceKey {
  const segments = key.split(INSTANCE_KEY_SEPARATOR);
  if (segments.length === 1) {
    return { date: key, kind: "daily", templateId: null, length: null };
  }
  const [date, templateId, length] = segments;
  return {
    date,
    kind: "template",
    templateId: templateId ?? null,
    length: isWorkoutLength(length) ? length : null,
  };
}

/** Whether `key` addresses a template (non-daily) instance. */
export function isTemplateInstanceKey(key: string): boolean {
  return key.includes(INSTANCE_KEY_SEPARATOR);
}

/* ------------------------------------------------------------------ *
 * Seeds
 * ------------------------------------------------------------------ */

/**
 * Canonical seed of the DAILY selection for `(date, attempt)` — mirrors the
 * format built inline in `today.ts` (`workout::<date>::<attempt>`). Kept as a
 * local constant here (instead of refactoring today.ts) so the frozen daily
 * path is untouched; a test pins the two formats together.
 */
export function dailySelectionSeed(date: string, attempt = 0): string {
  return `workout::${date}::${attempt}`;
}

/** Canonical seed of a TEMPLATE selection for its full identity tuple. */
export function templateSelectionSeed(
  date: string,
  templateId: string,
  length: WorkoutLength,
  attempt = 0,
): string {
  return `workout::${date}::${templateId}::${length}::${attempt}`;
}

/* ------------------------------------------------------------------ *
 * Factories + defensive parsing
 * ------------------------------------------------------------------ */

/** Build versioned metadata for a workout instance. */
export function createWorkoutMetadata(input: {
  kind: WorkoutKind;
  templateId: string;
  length: WorkoutLength;
  focus: GameCategory | null;
  inputs?: WorkoutGenerationInputs;
  /** Selector version used to produce the recorded order (V3+ rows). */
  selectionVersion?: number;
  /** Creation-time selection reasons (persisted when provided). */
  reasons?: WorkoutSelectionReason[];
}): WorkoutMetadata {
  return {
    version: WORKOUT_METADATA_VERSION,
    kind: input.kind,
    templateId: input.templateId,
    length: input.length,
    focus: input.focus,
    ...(input.inputs ? { inputs: input.inputs } : {}),
    ...(input.selectionVersion !== undefined
      ? { selectionVersion: input.selectionVersion }
      : {}),
    ...(input.reasons ? { reasons: [...input.reasons] } : {}),
  };
}

/**
 * Parse an unknown JSON value (a `metadata_json` cell) into
 * {@link WorkoutMetadata}, returning undefined for absent/malformed payloads
 * so one drifted row can never crash a history read (same policy as
 * `game_ids_json` parsing in db/workout.ts). A structurally valid
 * `inputs` snapshot round-trips; a malformed one is dropped while the rest of
 * the metadata survives (provenance is best-effort, never load-bearing).
 */
export function parseWorkoutMetadata(raw: unknown): WorkoutMetadata | undefined {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return undefined;
  }
  const value = raw as Record<string, unknown>;
  if (
    typeof value.version !== "number" ||
    (value.kind !== "daily" && value.kind !== "template") ||
    typeof value.templateId !== "string" ||
    !isWorkoutLength(value.length)
  ) {
    return undefined;
  }
  const focus =
    typeof value.focus === "string" ? (value.focus as GameCategory) : null;
  const rawInputs = value.inputs;
  let inputs: WorkoutGenerationInputs | undefined;
  if (typeof rawInputs === "object" && rawInputs !== null && !Array.isArray(rawInputs)) {
    const candidate = rawInputs as Record<string, unknown>;
    // All-or-nothing: a snapshot that lost any entry would silently change
    // what "re-running the recorded inputs" reproduces, so it is dropped whole.
    const domainRatingsOk =
      typeof candidate.domainRatings === "object" &&
      candidate.domainRatings !== null &&
      !Array.isArray(candidate.domainRatings) &&
      Object.values(candidate.domainRatings).every(
        (rating) => typeof rating === "number" && Number.isFinite(rating),
      );
    const recentOk =
      Array.isArray(candidate.recentGameIds) &&
      candidate.recentGameIds.every((id) => typeof id === "string");
    const evidence = parseEvidence(candidate);
    inputs =
      domainRatingsOk &&
      recentOk &&
      typeof candidate.seed === "string" &&
      evidence.valid
        ? {
            domainRatings: { ...(candidate.domainRatings as Record<string, number>) },
            recentGameIds: [...(candidate.recentGameIds as string[])],
            seed: candidate.seed,
            ...(evidence.aggregates
              ? { aggregates: evidence.aggregates }
              : {}),
            ...(evidence.recentSessions
              ? { recentSessions: evidence.recentSessions }
              : {}),
            ...(evidence.nowMs !== undefined ? { nowMs: evidence.nowMs } : {}),
          }
        : undefined;
  }
  const reasons = parseRecordedReasons(value.reasons);
  return {
    version: value.version,
    kind: value.kind,
    templateId: value.templateId,
    length: value.length,
    focus,
    ...(inputs ? { inputs } : {}),
    ...(Number.isSafeInteger(value.selectionVersion) &&
    (value.selectionVersion as number) >= 1
      ? { selectionVersion: value.selectionVersion as number }
      : {}),
    ...(reasons ? { reasons } : {}),
  };
}

function parseEvidence(candidate: Record<string, unknown>): {
  valid: boolean;
  aggregates?: WorkoutAggregateEvidence[];
  recentSessions?: WorkoutRecentSessionEvidence[];
  nowMs?: number;
} {
  const has = (key: string): boolean =>
    Object.prototype.hasOwnProperty.call(candidate, key);
  let aggregates: WorkoutAggregateEvidence[] | undefined;
  if (has("aggregates")) {
    if (!Array.isArray(candidate.aggregates)) return { valid: false };
    aggregates = [];
    for (const raw of candidate.aggregates) {
      if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
        return { valid: false };
      }
      const entry = raw as Record<string, unknown>;
      if (
        typeof entry.gameId !== "string" ||
        entry.gameId.length === 0 ||
        !Number.isFinite(entry.count) ||
        !Number.isFinite(entry.avgNormalized) ||
        !Number.isFinite(entry.bestNormalized) ||
        !Number.isSafeInteger(entry.lastCompletedAt)
      ) {
        return { valid: false };
      }
      aggregates.push({
        gameId: entry.gameId,
        count: entry.count as number,
        avgNormalized: entry.avgNormalized as number,
        bestNormalized: entry.bestNormalized as number,
        lastCompletedAt: entry.lastCompletedAt as number,
      });
    }
  }

  let recentSessions: WorkoutRecentSessionEvidence[] | undefined;
  if (has("recentSessions")) {
    if (!Array.isArray(candidate.recentSessions)) return { valid: false };
    recentSessions = [];
    for (const raw of candidate.recentSessions) {
      if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
        return { valid: false };
      }
      const entry = raw as Record<string, unknown>;
      if (
        typeof entry.gameId !== "string" ||
        entry.gameId.length === 0 ||
        !Number.isFinite(entry.normalizedResult) ||
        !Number.isSafeInteger(entry.completedAt)
      ) {
        return { valid: false };
      }
      recentSessions.push({
        gameId: entry.gameId,
        normalizedResult: entry.normalizedResult as number,
        completedAt: entry.completedAt as number,
      });
    }
  }

  let nowMs: number | undefined;
  if (has("nowMs")) {
    if (!Number.isSafeInteger(candidate.nowMs)) return { valid: false };
    nowMs = candidate.nowMs as number;
  }
  return { valid: true, aggregates, recentSessions, nowMs };
}

/**
 * Validate a persisted `reasons` array (defensive, same policy as the
 * generation-inputs snapshot): every entry must carry a string `gameId`, a
 * known reason `kind` and a string `detail`; one malformed entry drops the
 * WHOLE array (a partially-valid provenance record would silently mislabel
 * positions). Absent/invalid input yields undefined so legacy rows keep
 * loading with no reasons instead of crashing a history read.
 */
const REASON_KINDS: readonly WorkoutSelectionReason["kind"][] = [
  "weak-domain",
  "stale-domain",
  "recency-avoided",
  "selected",
  "excluded",
  // Workout V3 (campaign 014, metadata v2): personalization-signal kinds.
  // V1 producers never wrote these; v1 readers that encounter them degrade
  // the whole recorded-reasons array to null (documented policy above).
  "undertrained-domain",
  "novelty",
  "performance-trend",
  "personal-best-proximity",
  "difficulty-fit",
  "overexposure",
];

function parseRecordedReasons(
  raw: unknown,
): WorkoutSelectionReason[] | undefined {
  if (!Array.isArray(raw)) {
    return undefined;
  }
  const parsed: WorkoutSelectionReason[] = [];
  for (const entry of raw) {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      return undefined;
    }
    const value = entry as Record<string, unknown>;
    if (
      typeof value.gameId !== "string" ||
      typeof value.detail !== "string" ||
      !REASON_KINDS.includes(value.kind as WorkoutSelectionReason["kind"])
    ) {
      return undefined;
    }
    parsed.push({
      gameId: value.gameId,
      kind: value.kind as WorkoutSelectionReason["kind"],
      detail: value.detail,
    });
  }
  return parsed;
}
