/**
 * Catalog-wide structural contract, parameterized over the GENERATED
 * REGISTRY (not the raw games directory).
 *
 * Placement note: this lives in `src/test-utils` because it is the one
 * catalog-wide guard owned by the test-infrastructure packet; it enforces
 * STRUCTURE only (canonical module file set + valid `game.json`). Behavioral
 * lifecycle/pause/QA/testID contracts across the catalog are owned by the
 * shared-SDK contract tests (`src/sdk`, `src/components/game-ui`) and are
 * deliberately not duplicated here.
 *
 * Why the registry and not `readdirSync(src/games)`: the registry is
 * generated by the parent orchestrator after swarm convergence, so games
 * under active construction by other workers (present on disk but not yet
 * registered) do not produce transient failures here. Once a game IS
 * registered, it must ship the complete canonical file set — mirroring the
 * module template in `docs/GAME_SDK.md` /
 * `src/games/memory-grid-recall/` — or this guard fails.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from '@jest/globals';
import { registry } from '@/registry/registry.generated';

const GAMES_DIR = path.resolve(__dirname, '..', '..', 'games');

/** Files every registered game module must ship (see template). */
const CANONICAL_FILES = [
  'game.json',
  'game-definition.ts',
  'types.ts',
  'difficulty.ts',
  'generator.ts',
  'reducer.ts',
  'scoring.ts',
  'session.ts',
  'hooks.ts',
  'screen.tsx',
  'index.ts',
  'versions.ts',
] as const;

/** Directories every registered game module must ship. */
const CANONICAL_DIRS = ['components', '__tests__'] as const;

describe('catalog structure (parameterized over the generated registry)', () => {
  it('registers a non-empty catalog', () => {
    expect(registry.length).toBeGreaterThan(0);
  });

  it.each(registry.map((game) => game.id))(
    '%s ships the canonical module file set',
    (gameId) => {
      const dir = path.join(GAMES_DIR, gameId);
      const missingFiles = CANONICAL_FILES.filter(
        (file) => !existsSync(path.join(dir, file)),
      );
      expect(missingFiles).toEqual([]);

      const missingDirs = CANONICAL_DIRS.filter(
        (d) => !existsSync(path.join(dir, d)),
      );
      expect(missingDirs).toEqual([]);
    },
  );

  it.each(registry.map((game) => game.id))(
    '%s has a well-formed game.json',
    (gameId) => {
      const raw = readFileSync(
        path.join(GAMES_DIR, gameId, 'game.json'),
        'utf8',
      );
      const manifest = JSON.parse(raw) as Record<string, unknown>;

      expect(manifest.id).toBe(gameId);
      for (const key of [
        'name',
        'description',
        'primaryCategory',
        'sdkVersion',
        'gameVersion',
      ]) {
        // Key/value pair makes the failing field obvious in the diff.
        expect({ key, type: typeof manifest[key] }).toEqual({
          key,
          type: 'string',
        });
      }
      expect((manifest.name as string).length).toBeGreaterThan(0);
      expect((manifest.description as string).length).toBeGreaterThan(0);

      // Procedural games ship a generatorVersion; curated-content games ship
      // generatorVersion: null with a contentVersion instead.
      expect(
        manifest.generatorVersion === null ||
          typeof manifest.generatorVersion === 'string',
      ).toBe(true);
      if (manifest.generatorVersion === null) {
        expect(typeof manifest.contentVersion).toBe('string');
      }
    },
  );
});
