/**
 * Next in Sequence game — shared types (Logic & Problem Solving).
 *
 * The game is a pure state machine over `LogicGameState` (see reducer.ts);
 * this module owns the vocabulary the reducer, the UI, the generator and the
 * persistence layer all consume. Each round shows a number sequence with the
 * next term missing; the player picks the continuation from four options
 * generated by `generator.ts` (a solver proves the puzzle is unambiguous).
 */
import type {
  DiagnosticMetadata,
  DifficultyLevel,
  DifficultyProfile,
  GameRawResult,
  GeneratorInfo,
} from '@/sdk';

/** Stable game id (must match game.json). Never rename once shipped. */
export const GAME_ID = 'logic-next-sequence';

/**
 * Recipe families that can generate a sequence. Each family defines a closed
 * rule (see generator.ts); the solver recognizes them in a fixed priority
 * order (arithmetic → geometric → squares → cubes → fibonacci → alternating →
 * increments), so every emitted puzzle has exactly one canonical reading.
 */
export type RecipeFamily =
  | 'arithmetic'
  | 'geometric'
  | 'squares'
  | 'cubes'
  | 'alternating'
  | 'fibonacci'
  | 'increments';

/**
 * Game-defined difficulty tuning; recorded in the resolved difficulty profile
 * (all numeric, per the SDK `resolveDifficulty` contract — the recipe pool is
 * encoded as the numeric `recipeTier`, see `RECIPE_TIERS` in generator.ts).
 */
export interface LogicDifficultyParams {
  /** Number of rounds in a session. */
  readonly rounds: number;
  /** Recipe-pool tier (0..3, see `RECIPE_TIERS`); also derives length/timing. */
  readonly recipeTier: number;
  /** Visible terms of the first (and every fixed-level) round. */
  readonly visibleLength: number;
  /** Inclusive lower bound for terms and options (0 — never negative). */
  readonly minValue: number;
  /** Inclusive upper bound for terms and options. */
  readonly maxValue: number;
  /** Reference response time in ms used by scoring/normalization. */
  readonly referenceMs: number;
  /** Adaptive-only: per-round recipe tier lower bound. */
  readonly minTier?: number;
  /** Adaptive-only: per-round recipe tier upper bound. */
  readonly maxTier?: number;
}

export type LogicPhase = 'intro' | 'question' | 'roundResult' | 'results';

/** Accumulated session statistics (all player-facing raw numbers). */
export interface LogicStats {
  readonly score: number;
  readonly roundsPlayed: number;
  readonly roundsPassed: number;
  readonly bestStreak: number;
  readonly streak: number;
  /** Sum of per-round response times (active time only, pause-free). */
  readonly totalMs: number;
  /** Sum of per-round reference times (the speed-normalization yardstick). */
  readonly targetMs: number;
  /** Fastest single-round response in ms; null before the first answer. */
  readonly fastestMs: number | null;
}

export const INITIAL_STATS: Readonly<LogicStats> = Object.freeze({
  score: 0,
  roundsPlayed: 0,
  roundsPassed: 0,
  bestStreak: 0,
  streak: 0,
  totalMs: 0,
  targetMs: 0,
  fastestMs: null,
});

/**
 * Raw result persisted with every completed session. Everything needed to
 * reconstruct the exact session is present: seed, versions, difficulty, and
 * generator details (see `generatorInfo` / `diagnosticMetadata`).
 */
export interface LogicRawResult extends GameRawResult {
  readonly score: number;
  readonly totalRounds: number;
  readonly roundsPlayed: number;
  readonly roundsPassed: number;
  readonly accuracy: number;
  readonly bestStreak: number;
  readonly totalMs: number;
  readonly targetMs: number;
  readonly fastestMs: number | null;
  readonly visibleLength: number;
  readonly recipeTier: number;
  readonly minValue: number;
  readonly maxValue: number;
  readonly referenceMs: number;
  /** Recipe tier of the final round (fixed levels: the level's constant tier). */
  readonly finalTier: number;
  readonly challengeRating: number;
  readonly difficulty: DifficultyLevel;
  readonly seed: string;
  readonly gameVersion: string;
  /** Null only for non-procedural games; this game always ships a generator. */
  readonly generatorVersion: string | null;
  readonly scoringVersion: string;
  /** True when the session was ended by a dev-only QA force hook. */
  readonly forced: boolean;
  readonly generatorInfo: GeneratorInfo;
  readonly diagnosticMetadata: DiagnosticMetadata;
}

/**
 * QA force-state patch keys supported by the game. Applied only in the
 * `intro` phase; unknown keys are ignored. Dev-only (see hooks.ts).
 */
export interface QaForceStatePatch extends Readonly<Record<string, unknown>> {
  /** Seed for the next session (QA reproducibility). */
  readonly seed?: string | number;
  /** Difficulty for the next session. */
  readonly difficulty?: DifficultyLevel;
}

export type LogicAction =
  | { type: 'select-difficulty'; level: DifficultyLevel }
  | { type: 'start-session'; seed: string; sessionId: string; startedAtMs: number }
  | { type: 'answer-option'; index: number; responseMs: number }
  | { type: 'next-round' }
  | { type: 'pause' }
  | { type: 'resume' }
  | { type: 'tutorial-open' }
  | { type: 'tutorial-close' }
  | {
      type: 'session-finalized';
      xp: number;
      normalized: number;
      activeDurationMs: number;
      pausedDurationMs: number;
      completedAtMs: number;
    }
  | { type: 'persistence-started' }
  | { type: 'persistence-succeeded' }
  | { type: 'persistence-failed'; message: string }
  | { type: 'qa/force-win' }
  | { type: 'qa/force-lose' }
  | { type: 'qa/force-state'; patch: QaForceStatePatch };

/** Complete game state; the screen renders this and dispatches actions. */
export interface LogicGameState {
  phase: LogicPhase;
  /** True while the SDK lifecycle is paused (timers frozen, puzzle obscured). */
  paused: boolean;
  /** Selected difficulty (preselected 'normal' in the intro). */
  difficulty: DifficultyLevel | null;
  /** Resolved difficulty profile for the active session. */
  profile: DifficultyProfile | null;
  /** QA-injected seed for the next session; null = random per session. */
  seedOverride: string | null;
  /** Canonical seed of the active session. */
  seed: string;
  sessionId: string | null;
  startedAtMs: number | null;
  completedAtMs: number | null;
  activeDurationMs: number;
  pausedDurationMs: number;
  /** 0-based index of the current round. */
  roundIndex: number;
  /** Recipe tier of the current round (adaptive moves it ±1 per round). */
  tier: number;
  /** Current round's puzzle (terms, options, answer); null in intro/results. */
  puzzle: LogicPuzzle | null;
  /** Index of the option the player tapped this round; null before answering. */
  selection: number | null;
  roundOutcome: 'passed' | 'failed' | null;
  /** Previous round's puzzle (near-duplicate avoidance + diagnostics). */
  prevPuzzle: LogicPuzzle | null;
  stats: LogicStats;
  forced: boolean;
  xp: number;
  normalized: number | null;
  persistState: 'idle' | 'started' | 'succeeded' | 'failed';
  /** Persistence failure detail (shown on the results screen). */
  lastError: string | null;
  tutorialOpen: boolean;
}

/** A generated puzzle: visible terms, four options, and the true continuation. */
export interface LogicPuzzle {
  /** Recipe family the solver identified (the canonical explanation). */
  readonly family: RecipeFamily;
  /** Visible terms the player reasons from. */
  readonly terms: readonly number[];
  /** The true next term (== terms' continuation under the family). */
  readonly answer: number;
  /** Four distinct options (shuffled); exactly one equals `answer`. */
  readonly options: readonly number[];
  /** Index of the correct option within `options`. */
  readonly answerIndex: number;
  /** Family parameters (used for the player-facing pattern description). */
  readonly params: Readonly<Record<string, number>>;
}

export function createInitialLogicState(): LogicGameState {
  return {
    phase: 'intro',
    paused: false,
    difficulty: 'normal',
    profile: null,
    seedOverride: null,
    seed: '',
    sessionId: null,
    startedAtMs: null,
    completedAtMs: null,
    activeDurationMs: 0,
    pausedDurationMs: 0,
    roundIndex: 0,
    tier: 1,
    puzzle: null,
    selection: null,
    roundOutcome: null,
    prevPuzzle: null,
    stats: { ...INITIAL_STATS },
    forced: false,
    xp: 0,
    normalized: null,
    persistState: 'idle',
    lastError: null,
    tutorialOpen: false,
  };
}
