/**
 * Game route — `/game/[id]`.
 *
 * Resolves the id from the generated game registry and renders the game's
 * screen through its lazy loader (`gameScreenLoaders`, generated by
 * `scripts/generate-game-registry.mjs`). Falls back to NotReady states for
 * unknown ids or registered-but-not-yet-implemented games.
 *
 * App-owned input envelope (Campaign 053): the route id and workout-launch
 * query values are validated through `@/routing/route-params` before any
 * registry lookup or session selection, so a malformed or oversized deep
 * link cannot select or persist a target.
 *
 * Note: tutorial persistence is hydrated from `getDb().tutorials` by
 * `usePersistentTutorialStore` before the game mounts and injected through the
 * screens' `tutorialStore` prop, so first-play completion survives process
 * death and help/replay still forces the tutorial. Games that omit the prop
 * keep the in-memory default for isolated unit tests.
 *
 * Task 10.1: Lazy-loaded game components are cached outside route render
 * to prevent unnecessary remounts from component identity changes.
 */

import { useLocalSearchParams } from "expo-router";
import { lazy, Suspense, useMemo, type ComponentType } from "react";
import { StyleSheet } from "react-native";

import { ErrorBoundary } from "@/components/error-boundary";
import { GameNotReady } from "@/components/game-not-ready";
import { ScreenShell } from "@/components/screen-shell";
import { ThemedText } from "@/components/themed-text";
import { ThemedView } from "@/components/themed-view";
import { Radii, Spacing } from "@/constants/theme";
import { getGameDefinition, getValidatedGameModule } from "@/registry/registry";
import { gameScreenLoaders } from "@/registry/registry.generated";
import { usePersistentTutorialStore } from "@/hooks/use-persistent-tutorial-store";
import { parseCanonicalGameId } from "@/routing/route-params";
import type { GameScreenProps } from "@/sdk";
import { WorkoutSessionLaunchProvider } from "@/workout/session-launch-context";
import { parseWorkoutLaunchProvenance } from "@/workout/session-provenance";

/**
 * Cache lazy-loaded game components to prevent unnecessary remounts.
 *
 * 074: every loader is wrapped so the module passes the SDK surface contract
 * (`default` must be a component, `gameDefinition` must be present) BEFORE its
 * component is used. A module that fails throws a named
 * `GameModuleSurfaceError` out of the lazy import, which React renders as the
 * error boundary's recoverable state instead of a blank screen — the guarantee
 * that matters is "a non-conforming module is never made available for
 * rendering", not "the shell looks healthy".
 */
const lazyComponentCache = new Map<string, ComponentType<GameScreenProps>>();

function getLazyGameComponent(gameId: string): ComponentType<GameScreenProps> | undefined {
  if (lazyComponentCache.has(gameId)) {
    return lazyComponentCache.get(gameId);
  }

  const loader = gameScreenLoaders[gameId];
  if (loader === undefined) {
    return undefined;
  }

  // The registry already owns the validating loader; reuse it rather than
  // duplicating the check here, so there is exactly one contract.
  const LazyComponent = lazy(async () => {
    const moduleSurface = await getValidatedGameModule(gameId);
    return { default: moduleSurface.default as ComponentType<GameScreenProps> };
  });
  lazyComponentCache.set(gameId, LazyComponent);
  return LazyComponent;
}

export default function GameScreen() {
  const { id, workoutKey, workoutIndex } = useLocalSearchParams<{
    id: string;
    workoutKey?: string | string[];
    workoutIndex?: string | string[];
  }>();
  // App-owned input envelope: a malformed or oversized id never reaches
  // registry lookup or workout-launch selection; it falls through to the
  // recoverable not-found presentation below.
  const routeGameId = parseCanonicalGameId(id);
  const game = routeGameId === null ? undefined : getGameDefinition(routeGameId);
  const workoutProvenance = useMemo(
    () =>
      parseWorkoutLaunchProvenance({
        gameId: routeGameId,
        instanceKey: workoutKey,
        legIndex: workoutIndex,
      }),
    [routeGameId, workoutKey, workoutIndex],
  );

  // Task 10.1: Cache the lazy component identity outside render (lazy creation is intentionally memoized).
  // Deps include `game` itself: getLazyGameComponent is a pure id-keyed cache
  // lookup, so recomputing on a new registry object is behavior-neutral while
  // keeping the hook dependency contract honest.
  // 074: the cast this line used to need is GONE — the generated loader map is
  // typed with `GameScreenProps`, so the screen's prop contract survives the
  // boundary. The previous `as ComponentType<{tutorialStore?: TutorialStore}>`
  // was unchecked, and it also had a side effect the linter could not see: a
  // type assertion makes the binding opaque, which suppressed the
  // `static-components` rule below. Now that the type is precise, the rule
  // fires — correctly in spirit, wrong in fact, because the identity IS stable:
  // `getLazyGameComponent` memoizes the `lazy()` result in a module-level Map
  // keyed by game id, so a re-render returns the identical component object and
  // cannot reset game state. The suppression is deliberate and narrow; if the
  // cache is ever removed, remove this too.
  const GameScreenComponent = useMemo(
    () => (game ? getLazyGameComponent(game.id) : undefined),
    [game],
  );

  // Hydrate the persisted tutorial state before the screen mounts; a mounted
  // screen reads the store during render, so hydrating later would flash the
  // first-play tutorial and then hide it. Unknown/unimplemented games skip it.
  // Screens all accept an optional `tutorialStore` injection seam. 074: that
  // seam is now a DECLARED prop (`GameScreenProps`) carried by the generated
  // loader map, so the cast this line used to need is gone. It was unchecked:
  // nothing verified that any game actually accepted the prop, so a screen
  // that renamed or dropped it would have compiled and then been handed an
  // object it did not understand.
  const tutorialStore = usePersistentTutorialStore(
    GameScreenComponent === undefined ? undefined : game?.id,
  );

  if (!game) {
    return (
      <ScreenShell>
        <ThemedText type="title" testID="game-title">
          Game
        </ThemedText>
        <GameNotReady variant="not-found" />
      </ScreenShell>
    );
  }

  return (
    <ScreenShell>
      {/* Title, category and description live in the game's intro hero
          (GameHost), which carries the `game-title` / `game-category` /
          `game-description` contract — rendering them here too duplicated the
          same three lines inside one viewport. The header still renders on the
          fallback path, where no game screen exists to own it. */}
      {GameScreenComponent ? null : (
        <>
          <ThemedText type="title" testID="game-title">
            {game.name}
          </ThemedText>
          <ThemedView type="accentSoft" style={styles.categoryPill} testID="game-category">
            <ThemedText type="caption" themeColor="accent">
              {game.primaryCategory}
            </ThemedText>
          </ThemedView>
          {game.description ? (
            <ThemedText type="small" themeColor="textSecondary" testID="game-description">
              {game.description}
            </ThemedText>
          ) : null}
        </>
      )}
      {GameScreenComponent ? (
        tutorialStore === null ? (
          // Hold the loading presentation until the persisted tutorial row is
          // known; mounting early would flash the first-play tutorial.
          <GameNotReady variant="loading" />
        ) : (
          <ErrorBoundary
            onError={(error, info) => {
              console.error(
                JSON.stringify({
                  level: "error",
                  component: "game-route",
                  gameId: game.id,
                  message: error.message,
                  stack: error.stack,
                  componentStack: info.componentStack,
                }),
              );
            }}
          >
            <Suspense fallback={<GameNotReady variant="loading" />}>
              <WorkoutSessionLaunchProvider provenance={workoutProvenance}>
                {/* eslint-disable-next-line react-hooks/static-components --
                    Identity is stable: `lazyComponentCache` is module-level and
                    keyed by game id, so this returns the same component object
                    on every render. See the note at the lookup above. */}
                <GameScreenComponent tutorialStore={tutorialStore} />
              </WorkoutSessionLaunchProvider>
            </Suspense>
          </ErrorBoundary>
        )
      ) : (
        <GameNotReady variant="not-implemented" />
      )}
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  categoryPill: {
    alignSelf: "flex-start",
    borderRadius: Radii.pill,
    paddingVertical: Spacing.half,
    paddingHorizontal: Spacing.twoHalf,
  },
});
