/**
 * Game route — `/game/[id]`.
 *
 * Resolves the id from the generated game registry and renders the game's
 * screen through its lazy loader (`gameScreenLoaders`, generated by
 * `scripts/generate-game-registry.mjs`). Falls back to NotReady states for
 * unknown ids or registered-but-not-yet-implemented games.
 */

import { useLocalSearchParams } from 'expo-router';
import { lazy, Suspense } from 'react';
import { StyleSheet } from 'react-native';

import { GameNotReady } from '@/components/game-not-ready';
import { ScreenShell } from '@/components/screen-shell';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Radii, Spacing } from '@/constants/theme';
import { getGameDefinition } from '@/registry/registry';
import { gameScreenLoaders } from '@/registry/registry.generated';

export default function GameScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const game = getGameDefinition(id ?? '');

  if (!game) {
    return (
      <ScreenShell>
        <ThemedText type="title" testID="game-title">
          Game
        </ThemedText>
        <GameNotReady variant="not-found" />
      </ScreenShell>
    );
  }

  const loader = gameScreenLoaders[game.id];
  const GameScreenComponent = loader !== undefined ? lazy(loader) : undefined;

  return (
    <ScreenShell>
      <ThemedText type="title" testID="game-title">
        {game.name}
      </ThemedText>
      <ThemedView type="accentSoft" style={styles.categoryPill} testID="game-category">
        <ThemedText type="caption" themeColor="accent">
          {game.primaryCategory}
        </ThemedText>
      </ThemedView>
      {game.description ? (
        <ThemedText type="small" themeColor="textSecondary" testID="game-description">
          {game.description}
        </ThemedText>
      ) : null}
      {GameScreenComponent ? (
        <Suspense fallback={<GameNotReady variant="loading" />}>
          <GameScreenComponent />
        </Suspense>
      ) : (
        <GameNotReady variant="not-implemented" />
      )}
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  categoryPill: {
    alignSelf: 'flex-start',
    borderRadius: Radii.pill,
    paddingVertical: Spacing.half,
    paddingHorizontal: Spacing.twoHalf,
  },
});
