/**
 * Game route — `/game/[id]`.
 *
 * Resolves the id from the generated game registry and renders the game's
 * screen through its lazy loader (`gameScreenLoaders`, generated by
 * `scripts/generate-game-registry.mjs`). Falls back to NotReady states for
 * unknown ids or registered-but-not-yet-implemented games.
 *
 * Note: tutorial persistence is hydrated from `getDb().tutorials` by
 * `usePersistentTutorialStore` before the game mounts and injected through the
 * screens' `tutorialStore` prop, so first-play completion survives process
 * death and help/replay still forces the tutorial. Games that omit the prop
 * keep the in-memory default for isolated unit tests.
 *
 * Task 10.1: Lazy-loaded game components are cached outside route render
 * to prevent unnecessary remounts from component identity changes.
 */

import { useLocalSearchParams } from "expo-router";
import { lazy, Suspense, useMemo, type ComponentType } from "react";
import { StyleSheet } from "react-native";

import { ErrorBoundary } from "@/components/error-boundary";
import { GameNotReady } from "@/components/game-not-ready";
import { ScreenShell } from "@/components/screen-shell";
import { ThemedText } from "@/components/themed-text";
import { ThemedView } from "@/components/themed-view";
import { Radii, Spacing } from "@/constants/theme";
import { getGameDefinition } from "@/registry/registry";
import { gameScreenLoaders } from "@/registry/registry.generated";
import { usePersistentTutorialStore } from "@/hooks/use-persistent-tutorial-store";
import type { TutorialStore } from "@/sdk";
import { WorkoutSessionLaunchProvider } from "@/workout/session-launch-context";
import { parseWorkoutLaunchProvenance } from "@/workout/session-provenance";

/** Cache lazy-loaded game components to prevent unnecessary remounts */
const lazyComponentCache = new Map<string, React.ComponentType>();

function getLazyGameComponent(gameId: string): React.ComponentType | undefined {
  if (lazyComponentCache.has(gameId)) {
    return lazyComponentCache.get(gameId);
  }

  const loader = gameScreenLoaders[gameId];
  if (loader === undefined) {
    return undefined;
  }

  const LazyComponent = lazy(loader);
  lazyComponentCache.set(gameId, LazyComponent);
  return LazyComponent;
}

export default function GameScreen() {
  const { id, workoutKey, workoutIndex } = useLocalSearchParams<{
    id: string;
    workoutKey?: string | string[];
    workoutIndex?: string | string[];
  }>();
  const game = getGameDefinition(id ?? "");
  const workoutProvenance = useMemo(
    () =>
      parseWorkoutLaunchProvenance({
        gameId: id,
        instanceKey: workoutKey,
        legIndex: workoutIndex,
      }),
    [id, workoutKey, workoutIndex],
  );

  // Task 10.1: Cache the lazy component identity outside render (lazy creation is intentionally memoized).
  // Deps include `game` itself: getLazyGameComponent is a pure id-keyed cache
  // lookup, so recomputing on a new registry object is behavior-neutral while
  // keeping the hook dependency contract honest.
  const GameScreenComponent = useMemo(
    () => (game ? getLazyGameComponent(game.id) : undefined),
    [game],
  );

  // Hydrate the persisted tutorial state before the screen mounts; a mounted
  // screen reads the store during render, so hydrating later would flash the
  // first-play tutorial and then hide it. Unknown/unimplemented games skip it.
  const tutorialStore = usePersistentTutorialStore(
    GameScreenComponent === undefined ? undefined : game?.id,
  );
  // Screens all accept an optional `tutorialStore` injection seam; the shared
  // loader type is the bare ComponentType, so widen it here once. Rendering is
  // guarded by the `GameScreenComponent` branch below.
  const InjectableGameComponent = GameScreenComponent as ComponentType<{
    tutorialStore?: TutorialStore;
  }>;

  if (!game) {
    return (
      <ScreenShell>
        <ThemedText type="title" testID="game-title">
          Game
        </ThemedText>
        <GameNotReady variant="not-found" />
      </ScreenShell>
    );
  }

  return (
    <ScreenShell>
      {/* Title, category and description live in the game's intro hero
          (GameHost), which carries the `game-title` / `game-category` /
          `game-description` contract — rendering them here too duplicated the
          same three lines inside one viewport. The header still renders on the
          fallback path, where no game screen exists to own it. */}
      {GameScreenComponent ? null : (
        <>
          <ThemedText type="title" testID="game-title">
            {game.name}
          </ThemedText>
          <ThemedView type="accentSoft" style={styles.categoryPill} testID="game-category">
            <ThemedText type="caption" themeColor="accent">
              {game.primaryCategory}
            </ThemedText>
          </ThemedView>
          {game.description ? (
            <ThemedText type="small" themeColor="textSecondary" testID="game-description">
              {game.description}
            </ThemedText>
          ) : null}
        </>
      )}
      {GameScreenComponent ? (
        tutorialStore === null ? (
          // Hold the loading presentation until the persisted tutorial row is
          // known; mounting early would flash the first-play tutorial.
          <GameNotReady variant="loading" />
        ) : (
          <ErrorBoundary
            onError={(error, info) => {
              console.error(
                JSON.stringify({
                  level: "error",
                  component: "game-route",
                  gameId: game.id,
                  message: error.message,
                  stack: error.stack,
                  componentStack: info.componentStack,
                }),
              );
            }}
          >
            <Suspense fallback={<GameNotReady variant="loading" />}>
              <WorkoutSessionLaunchProvider provenance={workoutProvenance}>
                <InjectableGameComponent tutorialStore={tutorialStore} />
              </WorkoutSessionLaunchProvider>
            </Suspense>
          </ErrorBoundary>
        )
      ) : (
        <GameNotReady variant="not-implemented" />
      )}
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  categoryPill: {
    alignSelf: "flex-start",
    borderRadius: Radii.pill,
    paddingVertical: Spacing.half,
    paddingHorizontal: Spacing.twoHalf,
  },
});
